
services:
  api-gateway:
    build: ./backend/api_gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - intent-filter
      - agent


  intent-filter:
    build: ./backend/intent_filter
    container_name: intent-filter
    ports:
      - "8001:8001"
    env_file:
      - ./backend/intent_filter/.env

  agent:
    build: ./backend/agent
    container_name: agent
    ports:
      - "8037:8037"
    env_file:
      - ./backend/agent/.env

  classsificator:
    build: ./backend/classificator
    container_name: classificator
    ports:
      - "8100:8100"
    depends_on:
      - agent


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway